on:
  workflow_dispatch:

jobs:
  build:
    name: Build a package
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pacman -Syu --needed --noconfirm base-devel

      - name: Initialize a build user
        run: |
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chmod -R a+rw .

      - name: makepkg
        run: |
          sudo -H -u builder makepkg -sC --noconfirm
