on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize
        run: |
          pacman -Syu --needed --noconfirm base-devel
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chmod -R a+rw .

      - name: makepkg
        run: |
          sudo -H -u builder makepkg -sC --noconfirm

      - name: Parse .SRCINFO
        id: srcinfo
        run: |
          sudo -H -u builder makepkg --printsrcinfo > .SRCINFO
          echo "version=$(grep pkgver .SRCINFO | awk '{print $3}')-$(grep pkgrel .SRCINFO | awk '{print $3}')" >> $GITHUB_OUTPUT

      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.srcinfo.outputs.version }}
          tag_name: ${{ steps.srcinfo.outputs.version }}
          files:
            st-${{ steps.srcinfo.outputs.version }}-x86_64.pkg.tar.zst
